### ISSUE TITLE
Missing top padding in cad body

### ISSUE THREAD

**Issue by WillianGruber** [djibe/material#15]
Hello!

I'm using latest release of material in [Blazorise](https://github.com/stsrki/Blazorise) and noticed card body is missing top padding:
![image](https://user-images.githubusercontent.com/56033692/88447888-8b4a7c80-ce0e-11ea-9fa5-58a627ccca75.png)
![image](https://user-images.githubusercontent.com/56033692/88447890-930a2100-ce0e-11ea-9bfc-91f293343a1b.png)

Could you check this, please?

Thank you!

**Comment by djibe** [comment]
Hi, this is a feature, not a bug :D
In order to acheive those cards (https://djibe.github.io/material/docs/4.5/material/cards/) while offering liberty to use a card-header, I set
```
.card-header + .card-body {
  margin-top: 0;
}
```
Feel free to add a padding utility to your card-body like ```.pt-3```.

Tell me if you see aother solution to this problem.
Thanks for reporting this.

**Comment by stsrki** [comment]
I also agree with @WillianGruber that this behavior is not good. I checked with old daemonite, bootstrap and also some other material frameworks and all of them have some padding or margin between header and body parts.

btw, you have padding set instead of margin

```css
.card-header+.card-body {
    padding-top: 0;
}
```

**Comment by djibe** [comment]
Sorry, I was thinking of padding and wrote margin.

I'll do it

**Comment by djibe** [comment]
Sources in repo updated.
