### ISSUE TITLE
White Overlay on Button

### ISSUE THREAD

**Issue by gaurav2103** [djibe/material#33]
![image](https://user-images.githubusercontent.com/31451584/113985623-00a99080-986a-11eb-8101-682241111472.png)

When I click on the reset button a white overlay comes on button again if I click it goes.

I don't want this how to achieve this

I want a button like this 
![image](https://user-images.githubusercontent.com/31451584/113985933-4fefc100-986a-11eb-9ce3-8163eb64abc8.png)

**Comment by tbuyle** [comment]
It seems that this is due to the button being on focus.

See below for info on the CSS. But rather than changing the CSS, I'd recomend changing the behviour of you site / app so that, once reset is triggered, the button goes out of focus. Focused style are there for usability purpose.

The code for the white overlay in in _button.scss. Right after the 'Alternate buttons' comment, there is a loop trough $color, with rules for for &:focus,  &.focus.

The actual rule for the white overlay is

`background-image: linear-gradient(to bottom, rgba($white, $overlay-focus-colored-opacity), rgba($white, $overlay-focus-colored-opacity));`

You'll have to add you own css to set `background-image: none` to your button.

**Comment by gaurav2103** [comment]
@tbuyle thanks for the suggestions and help
